spring.application.name=TechLearnAPI
server.port=8080
spring.datasource.url=jdbc:sqlserver://TechLearnDB.mssql.somee.com;databaseName=TechLearnDB;integratedSecurity=false;encrypt=false;trustServerCertificate=true
spring.datasource.username=Migsk_
spring.datasource.password=TLDB123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

